# TCL File Generated by Component Editor 18.1
# Wed Jun 10 08:38:57 NZST 2026
# DO NOT MODIFY


# 
# noc_avalon_bridge "noc_avalon_bridge" v1.0
#  2026.06.10.08:38:57
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module noc_avalon_bridge
# 
set_module_property DESCRIPTION ""
set_module_property NAME noc_avalon_bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME noc_avalon_bridge
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL noc_avalon_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file noc_avalon_bridge.vhd VHDL PATH ../ip/noc_avalon_bridge/noc_avalon_bridge.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point noc
# 
add_interface noc conduit end
set_interface_property noc associatedClock clock
set_interface_property noc associatedReset reset
set_interface_property noc ENABLED true
set_interface_property noc EXPORT_OF ""
set_interface_property noc PORT_NAME_MAP ""
set_interface_property noc CMSIS_SVD_VARIABLES ""
set_interface_property noc SVD_ADDRESS_GROUP ""

add_interface_port noc coe_send_data coe_send_data Output 32
add_interface_port noc coe_recv_addr coe_recv_addr Input 8
add_interface_port noc coe_recv_data coe_recv_data Input 32
add_interface_port noc coe_send_addr coe_send_addr Output 8


# 
# connection point avs_1
# 
add_interface avs_1 avalon end
set_interface_property avs_1 addressUnits WORDS
set_interface_property avs_1 associatedClock clock
set_interface_property avs_1 associatedReset reset
set_interface_property avs_1 bitsPerSymbol 8
set_interface_property avs_1 burstOnBurstBoundariesOnly false
set_interface_property avs_1 burstcountUnits WORDS
set_interface_property avs_1 explicitAddressSpan 16
set_interface_property avs_1 holdTime 0
set_interface_property avs_1 linewrapBursts false
set_interface_property avs_1 maximumPendingReadTransactions 0
set_interface_property avs_1 maximumPendingWriteTransactions 0
set_interface_property avs_1 readLatency 0
set_interface_property avs_1 readWaitTime 1
set_interface_property avs_1 setupTime 0
set_interface_property avs_1 timingUnits Cycles
set_interface_property avs_1 writeWaitTime 0
set_interface_property avs_1 ENABLED true
set_interface_property avs_1 EXPORT_OF ""
set_interface_property avs_1 PORT_NAME_MAP ""
set_interface_property avs_1 CMSIS_SVD_VARIABLES ""
set_interface_property avs_1 SVD_ADDRESS_GROUP ""

add_interface_port avs_1 avs_address address Input 2
add_interface_port avs_1 avs_read read Input 1
add_interface_port avs_1 avs_write write Input 1
add_interface_port avs_1 avs_writedata writedata Input 32
add_interface_port avs_1 avs_readdata readdata Output 32
set_interface_assignment avs_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avs_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs_1 embeddedsw.configuration.isPrintableDevice 0

